### ISSUE TITLE
MultiLineString or LineString

### ISSUE THREAD

**Issue by gac55** [oobrien/vis#2]
Hi Oliver,

Thanks for sharing this, really useful.

One query - why do you use `MultiLineString` sometimes in the `tfl_lines.json` when you only ever have a polyline of length one? 

I'm trying to understand what is the difference between the lines marked as `MultiLineString` and those as `LineString` as to me, from the contents of the `MultiLineString` it looks like they should be labelled as a `LineString`

Thanks!

Gerry

**Comment by oobrien** [comment]
Hi Gerry - this is a hangover from when I had one MultiLineString for each tube line, rather than having station-to-station segments. When I sliced up the lines, I didn't at that point change the MultiLineString to LineString. I will push an update now that does that.
